### ISSUE TITLE
Add config menu & Multiplayer Warning

### ISSUE THREAD

**Issue by Scarlaid** [artemisSystem/better-climbing#1]
![image](https://user-images.githubusercontent.com/90851437/209474994-ddb14de7-a044-4865-ac08-f8ea1cec5e96.png)

Unaware this mod could not be used in servers with AntiCheat, luckily this was my own server so no damage was done
As the title said, add a config menu, maybe [YetAnotherConfigLib](https://www.curseforge.com/minecraft/mc-mods/yacl) with a more specific description of the mod, like multiplayer risk of using

**Comment by artemisSystem** [comment]
While the mod technically works client only, that's an unintentional side effect, which is why this is marked "Client + Server" on both curseforge and modrinth. I considered that — along with the features of the mod itself — a clear enough warning to not do this. Though i've now also added a warning to both mod pages that this shouldn't be used clientside on vanilla servers.

Configs and a check so it only works on servers are things i might want to implement eventually, but i also don't want to push myself into it, i'd rather do it at my own pace. For that reason i also probably wouldn't accept contributions implementing them due to maintenance burden, and am going to close this issue for now too, sorry.

**Comment by teleheel** [comment]
Seeing as you closed this due to not wanting to implement configs at the time, I didn't want to create a new issue. But if/when you get to implementing configs (could just be a config file to start with), having config options allowing to set the increased climbing/falling speeds would be great. It would enable modpack makers (e.g. me) to better balance the usefulness of stairs vs. other means of vertical movement.

**Comment by artemisSystem** [comment]
Yeah, that is planned

I just need to find a good way to do configs on xplat

**Comment by thimblebird** [comment]
should we create a new issue for the configs?
